rtx.useVertexCapture = False
rtx.fusedWorldViewMode = 1
rtx.fogIgnoreSky = False
rtx.ignoreAllVertexColorBakedLighting = False
rtx.orthographicIsUI = True
rtx.vertexColorIsBakedLighting = False
rtx.useVertexCapturedNormals = False
rtx.allowCubemaps = False
rtx.enableAlwaysCalculateAABB = False
rtx.enableRaytracing = False
rtx.useWorldMatricesForShaders = False
