d3d9.psShaderModel = 2
d3d9.vsShaderModel = 2
rtx.useUnusedRenderstates = True
rtx.vertexColorStrength = 1.0
rtx.useVertexCapture = False
rtx.useVertexCapturedNormals = False
rtx.useWorldMatricesForShaders = False
rtx.orthographicIsUI = True
